// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'count-selector': string;
  'icon-star': string;
  'list': string;
  'list-item': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
