// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'large': string;
  'loader': string;
  'loader-container': string;
  'loader-img': string;
  'loader-text': string;
  'medium': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
