// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'search': string;
  'search-text': string;
  'video-duration': string;
  'wrapper': string;
  'youtube-search': string;
}
export const cssExports: CssExports;
export default cssExports;
