// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clear-btn': string;
  'drag-start': string;
  'playlist': string;
  'playlist-item': string;
}
export const cssExports: CssExports;
export default cssExports;
