// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'big': string;
  'game-card': string;
  'huge': string;
  'icon': string;
  'icons-container': string;
  'medium': string;
  'micra': string;
  'small': string;
  'sub-title': string;
  'tiny': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
