// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'item': string;
  'left': string;
  'navigation': string;
  'right': string;
  'thumbnail': string;
  'video-selector': string;
}
export const cssExports: CssExports;
export default cssExports;
