// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'score-star': string;
  'scoreboard': string;
}
export const cssExports: CssExports;
export default cssExports;
