// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'game-btn': string;
  'game-selector': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
